#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  5 10:57:48 2024
@author: Frederic Labbe
The original format of the details file generated by PHASTEST (which contain the predicted genes) could be difficult to work with.
This script reformats the details file generated by PHASTEST.
usage: python PhastestGenFOrm.py --inputfile '/path/to/file.txt'
"""

import os.path
import numpy as np
import pandas as pd
import itertools
import re
import argparse
import sys
pd.options.mode.chained_assignment = None
parser = argparse.ArgumentParser()
parser.add_argument('-i', "--inputfile", required = True, help = 'Path to the input file')
args = parser.parse_args()

def PhastestGenForm(inputfile):
    if os.path.exists(inputfile):
        os.chdir(os.path.dirname(os.path.abspath(inputfile)))
        outputfile = inputfile.split("/")[-1].split(".txt")[0] + "_format.txt"
        f = open(outputfile, 'w')
        f.write("REGION\tCDS_POSITION\tBLAST_HIT\tEVALUE\tPID\tGO_COMPONENT\tGO_FUNCTION\tGO_PROCESS\tprophage_PRO_SEQ\n".format())
        RE_COMBINE_WHITESPACE = re.compile(r"\s+")
        with open(inputfile, "rt") as ifile:
            for line in itertools.islice(ifile, 5, None):  # start=5, stop=None
                if line.startswith("####"):
                    line = line.split('####')
                    region = line[1]
                else:
                    if len(line.strip()) != 0 :
                        line1 = RE_COMBINE_WHITESPACE.sub(" ", str(line)).strip()
                        line2 = line1.split(' ')
                        CDS_POSITION = line2[0]
                        prophage_PRO_SEQ = line2[-1]
                        #if 'attL' in line2 or 'attR' in line2 or 'tRNA-Arg' in line2:
                        if len(line2) == 4:
                            BLAST_HIT = line2[1]
                            EVALUE = line2[2]
                            f.write("{}\t{}\t{}\t{}\tN/A\tN/A\tN/A\tN/A\t{}\n".format(region.replace(" ", ""), CDS_POSITION, BLAST_HIT, EVALUE, prophage_PRO_SEQ))
                        else:
                            BLAST_HIT = str(np.array(line2[1:-6]))
                            BLAST_HIT = BLAST_HIT.replace("'", "")
                            BLAST_HIT = BLAST_HIT.replace("\n", "")
                            EVALUE = line2[-6]
                            PID = line2[-5]
                            GO_COMPONENT = line2[-4]
                            GO_FUNCTION = line2[-3]
                            GO_PROCESS = line2[-2]            
                            f.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(region.replace(" ", ""), CDS_POSITION, BLAST_HIT[1:-1], EVALUE, PID, GO_COMPONENT, GO_FUNCTION, GO_PROCESS, prophage_PRO_SEQ))
        f.close()
    else:
       sys.exit('Error: provide a valid path to the input file')

if __name__ == '__main__':
    PhastestGenForm(args.inputfile)
